sudo: false

matrix:
  fast_finish: true
  include:
    - language: cpp
      os: osx
      osx_image: xcode8

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

script:
  - ./dev-install.sh
  - ./create-osx-bundle.sh
  - travis_wait 20 ./install-kivy-framework.sh master > /dev/null
