matrix:
  fast_finish: true
  include:
    - language: cpp
      os: osx
      osx_image: xcode8
    - language: cpp
      os: osx
      osx_image: xcode8.1

cache:
  timeout: 1000
  directories:
  - cache

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

install:
  - sudo chown -R $(whoami) /usr/local && ls -l /usr;

script:
  - ./dev-install.sh
  - ./create-osx-bundle.sh
  - ./install-kivy-framework.sh master
