sudo: false

matrix:
  fast_finish: true
  include:
    - language: cpp
      os: osx
      osx_image: xcode8

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

script:
  - chmod 744 dev-install.sh
  - ./dev-install.sh
  - chmod 744 create-osx-bundle.sh
  - ./create-osx-bundle.sh
  - chmod 744 install-kivy-framework.sh
  - ./install-kivy-framework.sh master
